name: CI
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
env:
  XCODE_PROJECT: VoiceAssistant.xcodeproj
  XCODE_SCHEME: VoiceAssistant
jobs:
  build-and-test:
    name: Build & Test
    strategy:
      fail-fast: false
      matrix:
        include:
          # For information about the runner images and the software each image contains,
          # refer to: https://github.com/actions/runner-images
          - os: macos-14
            xcode: 15.4
            platform: "iOS Simulator,OS=17.5,name=iPhone 15 Pro"
          - os: macos-14
            xcode: 15.4
            platform: "macOS"
          - os: macos-14
            xcode: 15.4
            platform: "macOS,variant=Mac Catalyst"
          - os: macos-14
            xcode: 15.4
            platform: "visionOS Simulator,name=Apple Vision Pro"
          - os: macos-15
            xcode: 16.2
            platform: "iOS Simulator,OS=18.1,name=iPhone 16 Pro"
          - os: macos-15
            xcode: 16.2
            platform: "macOS"
          - os: macos-15
            xcode: 16.2
            platform: "macOS,variant=Mac Catalyst"
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      ## Currently there are no tests that require the server to be running
      ## Uncomment this when adding tests that require the server to be running
      ## ------------------------------------------------------------------------
      # - name: Install LiveKit Server
      #  run: brew install livekit
      # - name: Run LiveKit Server
      #  run: livekit-server --dev &

      - name: Setup Xcode ${{ matrix.xcode }}
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode }}

      - name: Print Versions
        run: |
          xcodebuild -version
          xcrun swift --version

      # Cache key cannot contains commas
      - name: Generate Cache Key
        id: cache-key
        run: |
          SANITIZED_PLATFORM=$(echo "${{ matrix.platform }}" | tr ',' '-')
          echo "key=xcode-${{ matrix.xcode }}-${SANITIZED_PLATFORM}" >> $GITHUB_OUTPUT

      - name: Cache
        uses: irgaly/xcode-cache@v1
        with:
          key: ${{ steps.cache-key.outputs.key }}-${{ github.sha }}
          restore-keys: ${{ steps.cache-key.outputs.key }}-

      - name: Write Default Config
        run: cd VoiceAssistant && cat .env.example.xcconfig > .env.xcconfig

      - name: Build for Testing
        run: |
          set -o pipefail && xcodebuild build-for-testing \
            -project ${{ env.XCODE_PROJECT }} \
            -scheme ${{ env.XCODE_SCHEME }} \
            -destination 'platform=${{ matrix.platform }}' \
            CODE_SIGN_IDENTITY="" | xcbeautify --renderer github-actions

      ## This project does not currently have tests
      ## Uncomment this once they are added
      ## ------------------------------------------------------------------------
      # - name: Run Tests
      #  run: |
      #    set -o pipefail && xcodebuild test-without-building \
      #      -project ${{ env.XCODE_PROJECT }} \
      #      -scheme ${{ env.XCODE_SCHEME }} \
      #      -destination 'platform=${{ matrix.platform }}' \
      #      -parallel-testing-enabled YES \
      #      -parallel-testing-worker-count 4 | xcbeautify --renderer github-actions

      - name: Build for Release
        run: |
          set -o pipefail && xcodebuild build \
            -project ${{ env.XCODE_PROJECT }} \
            -scheme ${{ env.XCODE_SCHEME }} \
            -configuration Release \
            -destination 'platform=${{ matrix.platform }}' \
            CODE_SIGN_IDENTITY="" | xcbeautify --renderer github-actions
  lint:
    name: Lint
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: SwiftFormat Lint
        run: swiftformat --lint . --reporter github-actions-log
        # Comes pre-installed on macOS runners
